---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - gpg
    state: present
    update_cache: yes

- name: Add Grafana GPG key
  ansible.builtin.apt_key:
    url: "{{ alloy_grafana_gpg_key_url }}"
    keyring: /etc/apt/keyrings/grafana.gpg
    state: present

- name: Add Grafana repository
  ansible.builtin.copy:
    content: |
      Types: deb
      URIs: {{ alloy_grafana_apt_repo_url }}
      Suites: stable
      Components: main
      Signed-By: /etc/apt/keyrings/grafana.gpg
    dest: /etc/apt/sources.list.d/grafana.sources
    owner: root
    group: root
    mode: '0644'

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Alloy
  ansible.builtin.apt:
    name: alloy
    state: present