- name: Ensure /home directory exists with correct permissions
  ansible.builtin.file:
    path: "{{ create_home_dirs.home_base }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Ensure user home directories exist with correct ownership
  ansible.builtin.file:
    path: "{{ create_home_dirs.home_base }}/{{ item.name }}"
    state: directory
    owner: "{{ item.uid }}"
    group: "{{ item.gid }}"
    mode: "0700"
  loop: "{{ user_list | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
