---
- name: Include OS-specific tasks
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family | lower }}.yml"
    - "default.yml"

- name: Create Alloy configuration
  ansible.builtin.template:
    src: config.alloy.j2
    dest: "{{ alloy_config_file }}"
    owner: root
    group: root
    mode: '0644'
  notify: reload alloy

- name: Add alloy user to systemd-journal group
  ansible.builtin.user:
    name: "{{ alloy_user }}"
    groups: "{{ alloy_systemd_journal_group }}"
    append: yes

- name: Ensure Alloy service is enabled and started
  ansible.builtin.systemd:
    name: alloy.service
    enabled: "{{ alloy_service_enabled }}"
    state: "{{ alloy_service_state }}"
    daemon_reload: true