---
- name: reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  changed_when: true

- name: run freeipa health export
  ansible.builtin.systemd:
    name: "{{ freeipa_health_service_name }}.service"
    state: started
  changed_when: true
