site_name: オペレーションナレッジ
site_url: https://hydratlas.github.io/ops-knowledge/
repo_url: https://github.com/hydratlas/ops-knowledge

# 最小限のテーマ設定
theme:
  name: material
  language: ja
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - search.suggest

# 最小限のプラグイン（自動ナビゲーション生成を含む）
plugins:
  - search:
      lang: ja
  - awesome-pages  # 自動ナビゲーション生成

# 基本的なMarkdown拡張（画像処理を含む）
markdown_extensions:
  - attr_list  # 画像サイズ指定等
  - admonition  # 注意書きブロック
  - toc:
      permalink: true