[project]
name = "ops-knowledge"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "mkdocs>=1.5.3,<1.7",
    "mkdocs-material>=9.5,<10.0",
    "mkdocs-awesome-pages-plugin>=2.9,<3.0",
]
