- name: Install NFS client package on Debian-based systems
  ansible.builtin.package:
    name: nfs-common
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Install NFS client package on RHEL-based systems
  ansible.builtin.package:
    name: nfs-utils
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

- name: Ensure NFS mount points exist
  file:
    path: "{{ item.value.path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop: "{{ mount_patterns | dict2items }}"
  when: mount_selectors is defined and item.key in mount_selectors

- name: Mount
  mount:
    path: "{{ item.value.path }}"
    src: "{{ item.value.src }}"
    fstype: "{{ item.value.fstype }}"
    opts: "{{ item.value.opts }}"
    state: "{{ item.value.state }}"
  loop: "{{ mount_patterns | dict2items }}"
  when: mount_selectors is defined and item.key in mount_selectors
