---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart pve-remove-subscription-notice.path
  ansible.builtin.systemd:
    name: pve-remove-subscription-notice.path
    state: restarted
