- name: Create or update VMs on Proxmox
  proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    # VMのIDはuniqueに管理
    vmid: "{{ item.vmid }}"
    node: "{{ item.node }}"
    name: "{{ item.name }}"
    # デフォルト値 from proxmox_common_defaults + 個別上書き
    memory: "{{ item.memory | default(proxmox_common_defaults.memory) }}"
    cputype: "{{ item.cputype | default(proxmox_common_defaults.cputype) }}"
    scsihw: "{{ item.scsihw | default(proxmox_common_defaults.scsihw) }}"
    net0: "{{ item.net0 | default(proxmox_common_defaults.net0) }}"
    storage: "{{ item.storage | default(proxmox_common_defaults.storage) }}"
    # その他の引数も同様に default 化
    # ...
    state: present
  loop: "{{ proxmox_vms }}"
  loop_control:
    label: "{{ item.name }}"

  #scsi: '{"scsi0":"zfs:cloudinit,size=4M", "scsi1":"zfs:0,import-from=${IMAGE_PATH},ssd=1"}'
  #scsi1: "${STORAGE}:0,import-from=${IMAGE_PATH},ssd=1" \
  #efidisk0: "${STORAGE}:0"
  #cicustom: "vendor=${SNIPPET_STORAGE}:snippets/qemu-guest-agent.yaml"
  #bootdisk: scsi1
  #ciupgrade: true
