---
- name: Check if cloudflared user exists
  ansible.builtin.getent:
    database: passwd
    key: "{{ cloudflared_user }}"
  register: cloudflared_user_check
  failed_when: false

- name: Create cloudflared user with subuid/subgid
  ansible.builtin.command:
    cmd: useradd -r -F -s /sbin/nologin -d /var/lib/{{ cloudflared_user }} -c "Cloudflare Tunnel user" -M {{ cloudflared_user }}
  when: cloudflared_user_check.ansible_facts.getent_passwd[cloudflared_user] is not defined

- name: Create cloudflared home directory
  ansible.builtin.file:
    path: /var/lib/{{ cloudflared_user }}
    state: directory
    owner: "{{ cloudflared_user }}"
    group: "{{ cloudflared_user }}"
    mode: "0755"

- name: Create cloudflared directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /etc/containers/systemd
    - "{{ cloudflared_config_dir }}"

- name: Check if lingering is enabled for cloudflared
  ansible.builtin.command: loginctl show-user {{ cloudflared_user }} --property=Linger
  register: linger_status
  changed_when: false
  failed_when: false

- name: Enable lingering for cloudflared user
  ansible.builtin.command: loginctl enable-linger {{ cloudflared_user }}
  when: linger_status.stdout != "Linger=yes"

- name: Get cloudflared user UID
  ansible.builtin.getent:
    database: passwd
    key: "{{ cloudflared_user }}"
  register: cloudflared_user_info

- name: Set cloudflared UID fact
  ansible.builtin.set_fact:
    cloudflared_uid: "{{ cloudflared_user_info.ansible_facts.getent_passwd[cloudflared_user][1] }}"

- name: Create cloudflared environment file
  ansible.builtin.template:
    src: cloudflared.env.j2
    dest: "{{ cloudflared_config_dir }}/cloudflared.env"
    owner: "{{ cloudflared_user }}"
    group: "{{ cloudflared_user }}"
    mode: "0600"
  notify: restart cloudflared

- name: Create Podman Quadlet container file
  ansible.builtin.template:
    src: cloudflared.container.j2
    dest: /etc/containers/systemd/cloudflared.container
    owner: root
    group: root
    mode: "0644"
  notify: restart cloudflared