---
# Tasks for cloudflared role (k3s deployment)

- name: Create cloudflared namespace
  kubernetes.core.k8s:
    name: "{{ cloudflared_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
  run_once: true

- name: Create cloudflared secret from template
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'cloudflared-secret.yaml.j2') | from_yaml }}"
    state: present
  run_once: true
  no_log: true

- name: Deploy cloudflared deployment
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'cloudflared-deployment.yaml.j2') | from_yaml }}"
    state: present
  run_once: true

- name: Wait for cloudflared deployment to be ready
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: "{{ cloudflared_deployment_name }}"
    namespace: "{{ cloudflared_namespace }}"
    wait: true
    wait_condition:
      type: Progressing
      status: "True"
      reason: NewReplicaSetAvailable
    wait_sleep: 10
    wait_timeout: 300
  run_once: true