- name: Install tzdata on Alpine Linux
  ansible.builtin.package:
    name: tzdata
    state: present
  when: ansible_os_family == 'Alpine'

- name: Set the system timezone
  community.general.timezone:
    name: "{{ timezone }}"
