- name: Install nfs-utils package on RedHat-based systems
  ansible.builtin.package:
    name: nfs-utils
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Install nfs-kernel-server package on Debian-based systems
  ansible.builtin.package:
    name: nfs-kernel-server
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Create NFS export directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: root
    group: root
    mode: "{{ item.mode | default('0755') }}"
  loop: "{{ nfs_exports }}"
  notify: Restart NFS service

- name: Configure /etc/exports from template
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
  notify: Reload NFS export configuration

- name: Start and enable NFS service on RedHat-based systems
  ansible.builtin.service:
    name: nfs-server
    state: started
    enabled: yes
  when: ansible_facts['os_family'] == "RedHat"

- name: Start and enable NFS service on Debian-based systems
  ansible.builtin.service:
    name: nfs-kernel-server
    state: started
    enabled: yes
  when: ansible_facts['os_family'] == "Debian"
