- name: Ensure nfs-utils is installed (RHEL-based)
  package:
    name: nfs-utils
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Ensure nfs-kernel-server is installed (Debian-based)
  package:
    name: nfs-kernel-server
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Write /etc/exports directly from variable
  copy:
    content: "{{ nfs_exports }}"
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
  notify: Restart NFS service

- name: Ensure nfs-utils is installed (RHEL-based)
  service:
    name: nfs-server
    state: started
    enabled: yes
  when: ansible_facts['os_family'] == "RedHat"

- name: Ensure nfs-kernel-server is installed (Debian-based)
  service:
    name: nfs-kernel-server
    state: started
    enabled: yes
  when: ansible_facts['os_family'] == "Debian"
