- name: Ensure nfs-utils is installed (RHEL-based)
  package:
    name: nfs-utils
    state: present
  when: ansible_os_family == "RedHat"

- name: Ensure nfs-kernel-server is installed (Debian-based)
  package:
    name: nfs-kernel-server
    state: present
  when: ansible_os_family == "Debian"

- name: Write /etc/exports directly from variable
  copy:
    content: "{{ nfs_exports }}"
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
  notify: Restart NFS service

- name: Ensure NFS service is started and enabled
  service:
    name: "{{ 'nfs-server' if ansible_os_family == 'RedHat' else 'nfs-kernel-server' }}"
    state: started
    enabled: yes
