---
- name: "Resolve snapshots path for snapper config '{{ snapper_cfg.name }}'"
  ansible.builtin.set_fact:
    snapper_snapshots_path: "{{ (snapper_cfg.path | regex_replace('/$', '')) ~ '/.snapshots' }}"

- name: "Check '{{ snapper_snapshots_path }}' existence"
  ansible.builtin.stat:
    path: "{{ snapper_snapshots_path }}"
  register: snapper_snapshots_dir

- name: "Create nested subvolume '{{ snapper_snapshots_path }}'"
  ansible.builtin.command:
    cmd: "btrfs subvolume create {{ snapper_snapshots_path }}"
  when: not snapper_snapshots_dir.stat.exists
  changed_when: true

- name: "Set ownership and mode for '{{ snapper_snapshots_path }}'"
  ansible.builtin.file:
    path: "{{ snapper_snapshots_path }}"
    owner: root
    group: root
    mode: "0750"
    state: directory
  when: not snapper_snapshots_dir.stat.exists

- name: "Place snapper config '{{ snapper_cfg.name }}' from template"
  ansible.builtin.copy:
    src: /usr/share/snapper/config-templates/default
    dest: "/etc/snapper/configs/{{ snapper_cfg.name }}"
    remote_src: true
    owner: root
    group: root
    mode: "0640"
    force: false

- name: "Set SUBVOLUME for snapper config '{{ snapper_cfg.name }}'"
  community.general.ini_file:
    path: "/etc/snapper/configs/{{ snapper_cfg.name }}"
    section: null
    option: SUBVOLUME
    value: "\"{{ snapper_cfg.path }}\""
    no_extra_spaces: true
    owner: root
    group: root
    mode: "0640"
