---
- name: Configure snapper
  ansible.builtin.include_tasks: install.yml
  when: snapper_configs | length > 0

- name: Uninstall snapper
  ansible.builtin.include_tasks: uninstall.yml
  when: snapper_configs | length == 0
