---
- name: Check if k3s is already installed
  systemd:
    name: k3s.service
  register: k3s_status
  failed_when: false

- name: Check if wget exists
  command: which wget
  register: wget_exists
  failed_when: false
  changed_when: false

- name: Check if curl exists
  command: which curl
  register: curl_exists
  failed_when: false
  changed_when: false

- name: Install wget if neither wget nor curl exists
  block:
    - name: Check package manager
      command: which {{ item }}
      register: pkg_manager_check
      failed_when: false
      changed_when: false
      loop:
        - apt
        - dnf

    - name: Install wget using apt
      apt:
        name: wget
        state: present
        update_cache: yes
      when: pkg_manager_check.results[0].rc == 0

    - name: Install wget using dnf
      dnf:
        name: wget
        state: present
      when: pkg_manager_check.results[1].rc == 0
  when: wget_exists.rc != 0 and curl_exists.rc != 0

- name: Install k3s using wget
  shell: wget -qO- https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s
  when: 
    - k3s_status.status.ActiveState is not defined or k3s_status.status.ActiveState != "active"
    - wget_exists.rc == 0 or (wget_exists.rc != 0 and curl_exists.rc != 0)

- name: Install k3s using curl
  shell: curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s
  when: 
    - k3s_status.status.ActiveState is not defined or k3s_status.status.ActiveState != "active"
    - wget_exists.rc != 0 and curl_exists.rc == 0

- name: Ensure k3s service is started and enabled
  systemd:
    name: k3s.service
    state: started
    enabled: yes
    daemon_reload: yes
