---
# Handlers for cloudflared role (k3s deployment)

- name: restart cloudflared deployment
  kubernetes.core.k8s:
    api_version: apps/v1
    kind: Deployment
    name: "{{ cloudflared_deployment_name }}"
    namespace: "{{ cloudflared_namespace }}"
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    definition:
      spec:
        template:
          metadata:
            annotations:
              kubectl.kubernetes.io/restartedAt: "{{ now(utc=True).isoformat() }}"
  run_once: true