---
- name: restart cloudflared user service
  ansible.builtin.systemd:
    name: cloudflared.service
    state: restarted
    daemon_reload: true
    scope: user
  become: true
  become_user: "{{ cloudflared_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ cloudflared_uid }}"

- name: reload sysctl
  ansible.builtin.command: sysctl --system
