---
# Handlers for cloudflared role

- name: restart cloudflared
  ansible.builtin.systemd:
    name: "{{ cloudflared_container_name }}.service"
    state: restarted
    daemon_reload: yes

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: reload sysctl
  ansible.builtin.command: sysctl --system