- name: Ensure ssh_host_key directories exist
  ansible.builtin.file:
    path: "/mnt/pve/virtiofs-share/{{ item.vmid }}/ssh_host_key"
    state: directory
    owner: root
    group: root
    mode: '0700'
  loop: "{{ pve_vm_ssh_host_keys | default([]) }}"

- name: Deploy SSH private host key
  ansible.builtin.copy:
    content: "{{ item.key }}"
    dest: "/mnt/pve/virtiofs-share/{{ item.vmid }}/ssh_host_key/ssh_host_ed25519_key"
    owner: root
    group: root
    mode: '0600'
  loop: "{{ pve_vm_ssh_host_keys | default([]) }}"

- name: Deploy SSH public host key
  ansible.builtin.copy:
    content: "{{ item.key_pub }}"
    dest: "/mnt/pve/virtiofs-share/{{ item.vmid }}/ssh_host_key/ssh_host_ed25519_key.pub"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ pve_vm_ssh_host_keys | default([]) }}"
