- name: Ensure packages are updated (Debian-based)
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: dist
  when: ansible_os_family == "Debian"

- name: Ensure packages are updated (RHEL-based)
  dnf:
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"
