---
- name: Backup enterprise repository file
  ansible.builtin.command:
    cmd: mv /etc/apt/sources.list.d/pve-enterprise.list /etc/apt/sources.list.d/pve-enterprise.list.bak
    creates: /etc/apt/sources.list.d/pve-enterprise.list.bak
    removes: /etc/apt/sources.list.d/pve-enterprise.list
  notify: update apt cache

- name: Backup ceph repository file
  ansible.builtin.command:
    cmd: mv /etc/apt/sources.list.d/ceph.list /etc/apt/sources.list.d/ceph.list.bak
    creates: /etc/apt/sources.list.d/ceph.list.bak
    removes: /etc/apt/sources.list.d/ceph.list
  notify: update apt cache

- name: Create PVE no-subscription repository
  ansible.builtin.copy:
    content: |
      Types: deb
      URIs: http://download.proxmox.com/debian/pve
      Suites: {{ ansible_distribution_release }}
      Components: pve-no-subscription
    dest: /etc/apt/sources.list.d/pve-no-subscription.sources
    owner: root
    group: root
    mode: '0644'
  notify: update apt cache

- name: Create Ceph no-subscription repository
  ansible.builtin.copy:
    content: |
      Types: deb
      URIs: http://download.proxmox.com/debian/ceph-{{ ceph_version }}
      Suites: {{ ansible_distribution_release }}
      Components: no-subscription
    dest: /etc/apt/sources.list.d/ceph.sources
    owner: root
    group: root
    mode: '0644'
  notify: update apt cache