- name: Ensure SSH configuration directory exists
  file:
    path: /etc/ssh/sshd_config.d
    state: directory
    mode: '0755'

- name: Deploy jamp SSH configuration
  template:
    src: "10-ssh-jamp.conf.j2"
    dest: "/etc/ssh/sshd_config.d/10-ssh-jamp.conf"
    owner: root
    group: root
    mode: '0644'
  notify: Reload SSH
