- name: Ensure packages are updated (Debian-based)
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: dist
  when: ansible_facts['os_family'] == "Debian"

- name: Ensure packages are updated (RHEL-based)
  ansible.builtin.dnf:
    name: '*'
    state: latest
  when: ansible_facts['os_family'] == "RedHat"
