---
- name: Include podman_rootless_quadlet_base role
  ansible.builtin.include_tasks: "../../infrastructure/container/podman_rootless_quadlet_base/tasks/main.yml"
  vars:
    quadlet_user: "{{ loki_user }}"
    quadlet_user_comment: "{{ loki_user_comment }}"
    quadlet_app_name: "{{ loki_app_name }}"

- name: Set Loki directory paths
  ansible.builtin.set_fact:
    loki_config_dir: "{{ quadlet_config_dir }}"
    loki_data_dir: "{{ quadlet_home }}/.local/share/loki"

- name: Create additional Loki directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ loki_user }}"
    group: "{{ loki_user }}"
    mode: '0755'
  loop:
    - "{{ loki_data_dir }}"

- name: Create monitoring network file
  ansible.builtin.template:
    src: monitoring.network.j2
    dest: "{{ quadlet_systemd_dir }}/monitoring.network"
    owner: "{{ loki_user }}"
    group: "{{ loki_user }}"
    mode: '0644'

- name: Create Loki configuration file
  ansible.builtin.template:
    src: loki.yaml.j2
    dest: "{{ loki_config_dir }}/loki.yaml"
    owner: "{{ loki_user }}"
    group: "{{ loki_user }}"
    mode: '0644'
  notify: restart loki

- name: Create Loki Quadlet container file
  ansible.builtin.template:
    src: loki.container.j2
    dest: "{{ quadlet_systemd_dir }}/loki.container"
    owner: "{{ loki_user }}"
    group: "{{ loki_user }}"
    mode: '0644'
  notify: reload systemd user daemon

- name: Enable and start Loki service
  ansible.builtin.systemd:
    name: loki.service
    enabled: yes
    state: started
    scope: user
  become: yes
  become_user: "{{ loki_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ quadlet_uid }}"