- name: Ensure mount points exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: "{{ item.mode | default('0755') }}"
  loop: "{{ mounts | default([]) }}"

- name: mounts
  ansible.builtin.mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    dump: "{{ item.dump }}"
    passno: "{{ item.passno }}"
    state: "{{ item.state }}"
  loop: "{{ mounts | default([]) }}"
