{
 "title": "Node Exporter Overview (Aggregated by Hosts)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * avg(1 - (node_memory_MemAvailable_bytes[1m] / node_memory_MemTotal_bytes[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_disk_read_bytes_total[1m]))",
     "legendFormat": "{{label_name}} - Read"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_disk_written_bytes_total[1m]))",
     "legendFormat": "{{label_name}} - Read"
    }
   ]
  },
  {
   "title": "Disk Usage (/)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{mountpoint=\"/\",fstype!~\"tmpfs|overlay\"} - node_filesystem_free_bytes{mountpoint=\"/\",fstype!~\"tmpfs|overlay\"}) by (instance) / sum(node_filesystem_size_bytes{mountpoint=\"/\",fstype!~\"tmpfs|overlay\"}) by (instance)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage (/home)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{mountpoint=\"/home\",fstype!~\"tmpfs|overlay\"} - node_filesystem_free_bytes{mountpoint=\"/home\",fstype!~\"tmpfs|overlay\"}) by (instance) / sum(node_filesystem_size_bytes{mountpoint=\"/home\",fstype!~\"tmpfs|overlay\"}) by (instance)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Recived",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_network_receive_bytes_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Transmit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_network_transmit_bytes_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(node_thermal_zone_temp{type=\"x86_pkg_temp\", zone=\"2\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(node_time_seconds - node_boot_time_seconds)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}