{
 "title": "VictoriaLogs Logs Overview",
 "tags": [
  "victorialogs",
  "logs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "hostname", "query": { "query": "" } },
   {
    "name": "unit",
    "query": {
     "query": "_stream:{hostname=~\"$hostname\"}"
    }
   },
   { "name": "priority", "query": { "query": "" } },
   { "name": "count_by", "query": { "query": "" } },
   { "name": "limit", "query": "50,100,250,500,1000" },
   { "name": "query" }
  ]
 },
 "panels": [
  {
   "title": "Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "_stream:{hostname=~\"$hostname\", unit=~\"$unit\"} priority:~\"$priority\" $query | stats by (hostname) count() logs",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Count by $count_by",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "_stream:{hostname=~\"$hostname\", unit=~\"$unit\"} priority:~\"$priority\" $query | stats by ($count_by) count() c | sort by (c desc) | limit 50",
     "legendFormat": "{{$count_by}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "_stream:{hostname=~\"$hostname\", unit=~\"$unit\"} priority:~\"$priority\" $query | sort by (_time desc) | limit $limit"
    }
   ]
  }
 ]
}