name: Deploy mdBook to GitHub Pages

on:
  # mainブランチへのプッシュ時に実行
  push:
    branches:
      - main
  # merge-docs-update.ymlの完了時に実行
  workflow_run:
    workflows: ["Merge docs-update branch"]
    types: [completed]
    branches: [main]
  # 手動実行も可能
  workflow_dispatch:

# GitHub Pagesへのデプロイに必要な権限
permissions:
  contents: read
  pages: write
  id-token: write

# 同時実行を制御
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # ビルドジョブ
  build:
    runs-on: ubuntu-latest
    # workflow_runで実行される場合は成功時のみ実行
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      # リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # 最小限のチェックアウト
          ref: main  # 常に最新のmainブランチをチェックアウト

      # mdBookのセットアップ
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: '0.4.51'

      # mdbook-auto-gen-summaryのインストール
      - name: Install mdbook-auto-gen-summary
        run: |
          cargo install mdbook-auto-gen-summary

      # SUMMARY.mdが存在しない場合は空ファイルを作成
      - name: Create empty SUMMARY.md if not exists
        run: |
          if [ ! -f src/SUMMARY.md ]; then
            touch src/SUMMARY.md
            echo "# Summary" > src/SUMMARY.md
          fi

      # mdBookサイトのビルド
      - name: Build mdBook site
        run: mdbook build

      # GitHub Pages用のアーティファクトをアップロード
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  # デプロイジョブ
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      # GitHub Pagesにデプロイ
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4