name: Deploy MkDocs to GitHub Pages

on:
  # mainブランチへのプッシュ時に実行
  push:
    branches:
      - main
  # merge-docs-update.ymlの完了時に実行
  workflow_run:
    workflows: ["Merge docs-update branch"]
    types: [completed]
    branches: [main]
  # 手動実行も可能
  workflow_dispatch:

# GitHub Pagesへのデプロイに必要な権限
permissions:
  contents: read
  pages: write
  id-token: write

# 同時実行を制御
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # ビルドジョブ
  build:
    runs-on: ubuntu-latest
    # workflow_runで実行される場合は成功時のみ実行
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      # リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # 最小限のチェックアウト

      # Pythonのセットアップ
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # uvキャッシュの設定
      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            .venv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml', '**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      # uvのインストール
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      # MkDocsと依存関係のインストール
      - name: Install MkDocs and dependencies
        run: |
          uv sync --no-dev

      # MkDocsでサイトをビルド
      - name: Build MkDocs site
        run: uv run mkdocs build --clean --strict

      # GitHub Pages用のアーティファクトをアップロード
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  # デプロイジョブ
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      # GitHub Pagesにデプロイ
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4