- name: Install Podman on RHEL-based systems
  ansible.builtin.dnf:
    name: podman
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Podman on Debian-based systems
  ansible.builtin.apt:
    name: podman
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
